#!/usr/bin/env bash
#
# Manual host validation runner for Gate 5/6 core checks.
# Starts a local API process in docker runtime mode, performs create/stop and
# routing/isolation checks, and writes evidence to a markdown file.
#
# Usage:
#   bash infra/host/validate-gate56.sh
#
# Optional env:
#   API_PORT=8000
#   PACK_IMAGE=medforge-pack-default:local
#   EVIDENCE_FILE=docs/host-validation-$(date +%F).md
#   DB_PATH=apps/api/gate-evidence.db

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
API_PORT="${API_PORT:-8000}"
API_URL="http://127.0.0.1:${API_PORT}"
PACK_IMAGE="${PACK_IMAGE:-medforge-pack-default:local}"
DB_PATH="${DB_PATH:-${ROOT_DIR}/apps/api/gate-evidence.db}"
EVIDENCE_FILE="${EVIDENCE_FILE:-${ROOT_DIR}/docs/host-validation-$(date +%F).md}"
API_LOG="${ROOT_DIR}/apps/api/.gate56-api.log"

USER_A="00000000-0000-0000-0000-0000000000a1"
USER_B="00000000-0000-0000-0000-0000000000b2"

API_PID=""
SESSION_ID_A=""
SLUG_A=""
SESSION_ID_B=""
SLUG_B=""

require_cmd() {
  local cmd="$1"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "ERROR: required command not found: ${cmd}"
    exit 1
  fi
}

record() {
  local line="$1"
  printf "%s\n" "${line}" | tee -a "${EVIDENCE_FILE}"
}

section() {
  local name="$1"
  printf "\n### %s\n\n" "${name}" | tee -a "${EVIDENCE_FILE}"
}

assert_eq() {
  local got="$1"
  local expected="$2"
  local context="$3"
  if [ "${got}" != "${expected}" ]; then
    echo "ERROR: ${context}: expected '${expected}', got '${got}'"
    exit 1
  fi
}

json_field() {
  local payload="$1"
  local expr="$2"
  python3 -c "import json,sys; data=json.load(sys.stdin); print(${expr})" <<<"${payload}"
}

cleanup() {
  local exit_code=$?
  if [ -n "${SESSION_ID_A}" ]; then
    curl -sS -X POST "${API_URL}/api/sessions/${SESSION_ID_A}/stop" -H "X-User-Id: ${USER_A}" >/dev/null 2>&1 || true
  fi
  if [ -n "${SESSION_ID_B}" ]; then
    curl -sS -X POST "${API_URL}/api/sessions/${SESSION_ID_B}/stop" -H "X-User-Id: ${USER_B}" >/dev/null 2>&1 || true
  fi
  docker ps -a --format '{{.ID}} {{.Names}}' | awk '/ mf-session-/{print $1}' | xargs -r docker rm -f >/dev/null 2>&1 || true
  if [ -n "${API_PID}" ]; then
    kill "${API_PID}" >/dev/null 2>&1 || true
    wait "${API_PID}" >/dev/null 2>&1 || true
  fi
  exit "${exit_code}"
}
trap cleanup EXIT

wait_for_api() {
  for _ in $(seq 1 60); do
    if curl -sS "${API_URL}/healthz" >/dev/null 2>&1; then
      return
    fi
    sleep 1
  done
  echo "ERROR: API did not become healthy at ${API_URL}"
  exit 1
}

start_local_api() {
  cd "${ROOT_DIR}/apps/api"
  if [ ! -d ".venv" ]; then
    echo "ERROR: apps/api/.venv not found. Create it first."
    exit 1
  fi
  rm -f "${DB_PATH}" "${API_LOG}"
  (
    # shellcheck source=/dev/null
    . .venv/bin/activate
    DATABASE_URL="sqlite:///${DB_PATH}" \
    PACK_IMAGE="${PACK_IMAGE}" \
    ALLOW_LEGACY_HEADER_AUTH=true \
    SESSION_RUNTIME_MODE=docker \
    SESSION_RUNTIME_USE_SUDO=true \
    PUBLIC_SESSIONS_NETWORK=medforge-public-sessions \
    WORKSPACE_ZFS_ROOT=tank/medforge/workspaces \
    SESSION_RECOVERY_ENABLED=true \
    SESSION_POLL_INTERVAL_SECONDS=5 \
    COOKIE_SECURE=false \
    COOKIE_DOMAIN='' \
    uvicorn app.main:app --host 0.0.0.0 --port "${API_PORT}" >"${API_LOG}" 2>&1
  ) &
  API_PID=$!
  wait_for_api
}

main() {
  require_cmd curl
  require_cmd docker
  require_cmd python3
  require_cmd zfs
  require_cmd sudo

  if ! sudo -n true >/dev/null 2>&1; then
    echo "ERROR: this script requires passwordless sudo (sudo -n)."
    exit 1
  fi

  if ! docker network inspect medforge-public-sessions >/dev/null 2>&1; then
    echo "ERROR: docker network 'medforge-public-sessions' not found."
    echo "Run: sudo bash infra/host/bootstrap-easy.sh"
    exit 1
  fi

  {
    echo "## Host Validation Evidence ($(date +%F))"
    echo ""
    echo "Generated by: \`infra/host/validate-gate56.sh\`"
    echo ""
    echo "Runtime:"
    echo "- API URL: \`${API_URL}\`"
    echo "- Pack image: \`${PACK_IMAGE}\`"
    echo "- DB path: \`${DB_PATH}\`"
  } >"${EVIDENCE_FILE}"

  start_local_api

  section "Create Sessions"
  local resp_a
  resp_a="$(curl -sS -X POST "${API_URL}/api/sessions" -H 'content-type: application/json' -H "X-User-Id: ${USER_A}" -d '{"tier":"PUBLIC"}')"
  record "- create A: \`${resp_a}\`"
  SESSION_ID_A="$(json_field "${resp_a}" "data['session']['id']")"
  SLUG_A="$(json_field "${resp_a}" "data['session']['slug']")"

  local resp_b
  resp_b="$(curl -sS -X POST "${API_URL}/api/sessions" -H 'content-type: application/json' -H "X-User-Id: ${USER_B}" -d '{"tier":"PUBLIC"}')"
  record "- create B: \`${resp_b}\`"
  SESSION_ID_B="$(json_field "${resp_b}" "data['session']['id']")"
  SLUG_B="$(json_field "${resp_b}" "data['session']['slug']")"

  local host_a
  host_a="s-${SLUG_A}.medforge.local"

  section "Gate 5 Auth Matrix"
  local code
  code="$(curl -sS -o /tmp/g5_unauth.out -w '%{http_code}' "${API_URL}/api/auth/session-proxy" -H "Host: ${host_a}")"
  assert_eq "${code}" "401" "unauthenticated session-proxy"
  record "- unauthenticated: \`${code}\` body=\`$(cat /tmp/g5_unauth.out)\`"

  code="$(curl -sS -o /tmp/g5_nonowner.out -w '%{http_code}' "${API_URL}/api/auth/session-proxy" -H "Host: ${host_a}" -H "X-User-Id: ${USER_B}")"
  assert_eq "${code}" "403" "non-owner session-proxy"
  record "- non-owner: \`${code}\` body=\`$(cat /tmp/g5_nonowner.out)\`"

  local headers
  headers="$(curl -sS -D - -o /tmp/g5_owner.out "${API_URL}/api/auth/session-proxy" -H "Host: ${host_a}" -H "X-User-Id: ${USER_A}" -H 'X-Upstream: evil-target:8080')"
  code="$(printf '%s\n' "${headers}" | awk 'NR==1{print $2}')"
  assert_eq "${code}" "200" "owner session-proxy"
  local upstream
  upstream="$(printf '%s\n' "${headers}" | awk 'tolower($1)=="x-upstream:"{print $2}' | tr -d '\r')"
  if [ -z "${upstream}" ]; then
    echo "ERROR: missing X-Upstream response header"
    exit 1
  fi
  record "- owner spoof attempt: \`${code}\` x-upstream=\`${upstream}\`"

  section "Gate 5 Isolation"
  local firewall_out
  firewall_out="$(sudo bash "${ROOT_DIR}/infra/firewall/setup.sh")"
  record "- firewall: \`${firewall_out}\`"

  set +e
  docker exec "mf-session-${SLUG_B}" curl -sS --max-time 3 "http://mf-session-${SLUG_A}:8080" >/tmp/g5_iso.out 2>/tmp/g5_iso.err
  local iso_rc=$?
  set -e
  if [ "${iso_rc}" -eq 0 ]; then
    echo "ERROR: isolation check unexpectedly succeeded."
    echo "stdout: $(cat /tmp/g5_iso.out)"
    exit 1
  fi
  record "- session B -> session A :8080 blocked (exit=\`${iso_rc}\`, stderr=\`$(cat /tmp/g5_iso.err)\`)"

  section "Gate 6 End-to-End Core"
  local gpu_line
  gpu_line="$(docker exec "mf-session-${SLUG_A}" nvidia-smi --query-gpu=name --format=csv,noheader | head -n1)"
  if [[ "${gpu_line}" != *NVIDIA* ]]; then
    echo "ERROR: unexpected GPU probe output: ${gpu_line}"
    exit 1
  fi
  record "- GPU in session A: \`${gpu_line}\`"

  local ws_line
  ws_line="$(docker exec "mf-session-${SLUG_A}" sh -lc 'echo alpha > /workspace/alpha.txt && cat /workspace/alpha.txt')"
  assert_eq "${ws_line}" "alpha" "workspace write/read"
  record "- workspace write/read: \`${ws_line}\`"

  local stop_a
  stop_a="$(curl -sS -X POST "${API_URL}/api/sessions/${SESSION_ID_A}/stop" -H "X-User-Id: ${USER_A}")"
  record "- stop A: \`${stop_a}\`"

  code="$(curl -sS -o /tmp/g5_stopped.out -w '%{http_code}' "${API_URL}/api/auth/session-proxy" -H "Host: ${host_a}" -H "X-User-Id: ${USER_A}")"
  assert_eq "${code}" "404" "stopped session-proxy"
  record "- stopped host check: \`${code}\` body=\`$(cat /tmp/g5_stopped.out)\`"

  local snapshot
  snapshot="$(zfs list -t snapshot -H -o name | rg "tank/medforge/workspaces/.*/${SESSION_ID_A}@stop-" | tail -n1 || true)"
  if [ -z "${snapshot}" ]; then
    echo "ERROR: snapshot not found for session ${SESSION_ID_A}"
    exit 1
  fi
  record "- snapshot: \`${snapshot}\`"

  local stop_b
  stop_b="$(curl -sS -X POST "${API_URL}/api/sessions/${SESSION_ID_B}/stop" -H "X-User-Id: ${USER_B}")"
  record "- stop B: \`${stop_b}\`"

  section "Residual Gaps"
  record "- Caddy wildcard websocket validation is not covered by this script."
  record "- Full browser UI flow validation is not covered by this script."

  section "API Log Snippet"
  record '```text'
  tail -n 80 "${API_LOG}" | tee -a "${EVIDENCE_FILE}"
  record '```'

  echo ""
  echo "Validation complete: ${EVIDENCE_FILE}"
}

main "$@"
