from __future__ import annotations

SCORING_MODE_SINGLE_REALTIME_HIDDEN = "single_realtime_hidden"
LEADERBOARD_RULE_BEST_PER_USER = "best_per_user"
EVALUATION_POLICY_CANONICAL_TEST_FIRST = "canonical_test_first"

DEFAULT_SCORING_MODE = SCORING_MODE_SINGLE_REALTIME_HIDDEN
DEFAULT_LEADERBOARD_RULE = LEADERBOARD_RULE_BEST_PER_USER
DEFAULT_EVALUATION_POLICY = EVALUATION_POLICY_CANONICAL_TEST_FIRST

SUPPORTED_SCORING_MODES: set[str] = {
    SCORING_MODE_SINGLE_REALTIME_HIDDEN,
}
SUPPORTED_LEADERBOARD_RULES: set[str] = {
    LEADERBOARD_RULE_BEST_PER_USER,
}
SUPPORTED_EVALUATION_POLICIES: set[str] = {
    EVALUATION_POLICY_CANONICAL_TEST_FIRST,
}
