"""initial_schema

Revision ID: 2474ec93cdb5
Revises:
Create Date: 2026-02-16 15:38:25.620232

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2474ec93cdb5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('bytes >= 0', name='ck_datasets_bytes_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_slug'), ['slug'], unique=True)

    op.create_table('gpu_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.Enum('PUBLIC', 'PRIVATE', 'BOTH', name='pack_tier'), nullable=False),
    sa.Column('image_ref', sa.String(length=255), nullable=False),
    sa.Column('image_digest', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deprecated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='role'), nullable=False),
    sa.Column('max_concurrent_sessions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_concurrent_sessions > 0', name='ck_users_max_sessions_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('competitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('competition_tier', sa.Enum('PUBLIC', 'PRIVATE', name='competition_tier'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='competition_status'), nullable=False),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('metric_version', sa.String(length=64), nullable=False),
    sa.Column('higher_is_better', sa.Boolean(), nullable=False),
    sa.Column('scoring_mode', sa.String(length=64), nullable=False),
    sa.Column('leaderboard_rule', sa.String(length=64), nullable=False),
    sa.Column('evaluation_policy', sa.String(length=64), nullable=False),
    sa.Column('competition_spec_version', sa.String(length=64), nullable=False),
    sa.Column('submission_cap_per_day', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('submission_cap_per_day > 0', name='ck_competitions_submission_cap_positive'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitions_slug'), ['slug'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('PUBLIC', 'PRIVATE', name='tier'), nullable=False),
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('STARTING', 'RUNNING', 'STOPPING', 'STOPPED', 'ERROR', name='session_status'), nullable=False),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.Column('gpu_active', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=8), nullable=False),
    sa.Column('workspace_zfs', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu_devices.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gpu_id', 'gpu_active', name='uq_sessions_gpu_active'),
    sa.UniqueConstraint('workspace_zfs')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_gpu_id'), ['gpu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_sessions_user_status', ['user_id', 'status'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=128), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('score_status', sa.Enum('QUEUED', 'SCORING', 'SCORED', 'FAILED', name='score_status'), nullable=False),
    sa.Column('score_error', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('row_count >= 0', name='ck_submissions_row_count_nonnegative'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_competition_created', ['competition_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index('ix_submissions_competition_status', ['competition_id', 'score_status'], unique=False)
        batch_op.create_index('ix_submissions_competition_user_created', ['competition_id', 'user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_user_id'), ['user_id'], unique=False)

    op.create_table('submission_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('primary_score', sa.Float(), nullable=False),
    sa.Column('score_components_json', sa.Text(), nullable=False),
    sa.Column('scorer_version', sa.String(length=64), nullable=False),
    sa.Column('metric_version', sa.String(length=64), nullable=False),
    sa.Column('evaluation_split_version', sa.String(length=64), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'scorer_version', 'metric_version', 'evaluation_split_version', 'manifest_sha256', name='uq_submission_scores_idempotent_run')
    )
    with op.batch_alter_table('submission_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_scores_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index('ix_submission_scores_competition_user_official', ['competition_id', 'user_id', 'is_official', 'created_at'], unique=False)
        batch_op.create_index('ix_submission_scores_submission_created', ['submission_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_scores_submission_id'), ['submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_scores_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_submission_scores_submission_id'))
        batch_op.drop_index('ix_submission_scores_submission_created')
        batch_op.drop_index('ix_submission_scores_competition_user_official')
        batch_op.drop_index(batch_op.f('ix_submission_scores_competition_id'))

    op.drop_table('submission_scores')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_user_id'))
        batch_op.drop_index('ix_submissions_competition_user_created')
        batch_op.drop_index('ix_submissions_competition_status')
        batch_op.drop_index(batch_op.f('ix_submissions_competition_id'))
        batch_op.drop_index('ix_submissions_competition_created')

    op.drop_table('submissions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_status')
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_slug'))
        batch_op.drop_index(batch_op.f('ix_sessions_pack_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_gpu_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitions_slug'))
        batch_op.drop_index(batch_op.f('ix_competitions_dataset_id'))

    op.drop_table('competitions')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('packs')
    op.drop_table('gpu_devices')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_slug'))

    op.drop_table('datasets')
    # ### end Alembic commands ###
