#!/usr/bin/env bash
#
# Phase 2 auth and session API contract validation.
# Runs targeted test lanes for cookie auth, origin checks, and session proxy rules.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PHASE_ID="phase2-auth-api"
RUN_ID="$(date -u +%Y%m%dT%H%M%SZ)"
EVIDENCE_DIR="${EVIDENCE_DIR:-${ROOT_DIR}/docs/evidence/$(date -u +%F)}"
EVIDENCE_FILE="${EVIDENCE_FILE:-${EVIDENCE_DIR}/${PHASE_ID}-${RUN_ID}.md}"
LOG_FILE="${LOG_FILE:-${EVIDENCE_DIR}/${PHASE_ID}-${RUN_ID}.log}"

PHASE_STATUS="INCONCLUSIVE"

usage() {
  cat <<'USAGE'
Usage: bash ops/host/validate-phase2-auth-api.sh

Optional env:
  EVIDENCE_DIR=docs/evidence/<date>
  EVIDENCE_FILE=<explicit markdown path>
  LOG_FILE=<explicit log path>
USAGE
}

require_cmd() {
  local cmd="$1"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "ERROR: required command not found: ${cmd}"
    exit 1
  fi
}

record() {
  local line="$1"
  printf "%s\n" "${line}" >>"${EVIDENCE_FILE}"
}

run_check() {
  local name="$1"
  local cmd="$2"

  record "### ${name}"
  record ""
  record '```bash'
  record "${cmd}"
  record '```'

  if eval "${cmd}" >>"${LOG_FILE}" 2>&1; then
    record "- status: PASS"
  else
    record "- status: FAIL"
    record "- log: \`${LOG_FILE}\`"
    exit 1
  fi
  record ""
}

cleanup() {
  local exit_code=$?
  if [ "${PHASE_STATUS}" != "PASS" ] && [ -f "${EVIDENCE_FILE}" ]; then
    record "## Verdict"
    record "- phase: \`${PHASE_ID}\`"
    record "- status: FAIL"
    record "- log: \`${LOG_FILE}\`"
  fi
  exit "${exit_code}"
}
trap cleanup EXIT

run_auth_contract_tests() {
  cd "${ROOT_DIR}/apps/api"

  if [ ! -d ".venv" ]; then
    echo "ERROR: apps/api/.venv not found."
    return 1
  fi

  # shellcheck source=/dev/null
  . .venv/bin/activate

  pytest -q \
    tests/test_api.py::test_signup_login_logout_cookie_flow \
    tests/test_api.py::test_me_requires_auth \
    tests/test_api.py::test_session_proxy_requires_auth \
    tests/test_api.py::test_session_proxy_returns_404_for_invalid_host \
    tests/test_api.py::test_session_proxy_enforces_owner_and_running \
    tests/test_auth_hardening.py::test_session_proxy_strips_spoofed_x_upstream \
    tests/test_auth_hardening.py::test_origin_matrix_allowed_origins \
    tests/test_auth_hardening.py::test_origin_matrix_rejected_origins \
    tests/test_auth_hardening.py::test_auth_signup_rate_limit_429 \
    tests/test_auth_hardening.py::test_auth_login_rate_limit_429 \
    tests/test_auth_hardening.py::test_logout_invalidates_token \
    tests/test_auth_hardening.py::test_idle_ttl_expires_session \
    tests/test_auth_hardening.py::test_max_ttl_expires_session \
    tests/test_control_plane.py::test_sessions_current_requires_auth \
    tests/test_control_plane.py::test_session_create_rejects_disallowed_origin \
    tests/test_control_plane.py::test_session_stop_rejects_disallowed_origin
}

main() {
  if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    usage
    exit 0
  fi

  mkdir -p "${EVIDENCE_DIR}"
  : >"${LOG_FILE}"

  {
    echo "## Phase 2 Auth and Session API Contract Evidence ($(date -u +%F))"
    echo ""
    echo "Generated by: \`ops/host/validate-phase2-auth-api.sh\`"
    echo ""
    echo "Runtime:"
    echo "- run id: \`${RUN_ID}\`"
    echo "- api tests path: \`apps/api/tests\`"
    echo ""
  } >"${EVIDENCE_FILE}"

  run_check "Auth and Session Contract Tests" "run_auth_contract_tests"

  PHASE_STATUS="PASS"
  record "## Verdict"
  record "- phase: \`${PHASE_ID}\`"
  record "- status: PASS"
  record "- log: \`${LOG_FILE}\`"

  echo "Validation complete: ${EVIDENCE_FILE}"
}

main "$@"
