#!/usr/bin/env bash
#
# Phase 3 session lifecycle and recovery validation.
# Combines runtime create/stop/snapshot witness with recovery-focused test lanes.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PHASE_ID="phase3-lifecycle-recovery"
RUN_ID="$(date -u +%Y%m%dT%H%M%SZ)"
EVIDENCE_DIR="${EVIDENCE_DIR:-${ROOT_DIR}/docs/evidence/$(date -u +%F)}"
EVIDENCE_FILE="${EVIDENCE_FILE:-${EVIDENCE_DIR}/${PHASE_ID}-${RUN_ID}.md}"
LOG_FILE="${LOG_FILE:-${EVIDENCE_DIR}/${PHASE_ID}-${RUN_ID}.log}"

PHASE_STATUS="INCONCLUSIVE"

usage() {
  cat <<'USAGE'
Usage: bash ops/host/validate-phase3-lifecycle-recovery.sh

Optional env:
  EVIDENCE_DIR=docs/evidence/<date>
  EVIDENCE_FILE=<explicit markdown path>
  LOG_FILE=<explicit log path>
USAGE
}

require_cmd() {
  local cmd="$1"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "ERROR: required command not found: ${cmd}"
    exit 1
  fi
}

record() {
  local line="$1"
  printf "%s\n" "${line}" >>"${EVIDENCE_FILE}"
}

run_check() {
  local name="$1"
  local cmd="$2"

  record "### ${name}"
  record ""
  record '```bash'
  record "${cmd}"
  record '```'

  if eval "${cmd}" >>"${LOG_FILE}" 2>&1; then
    record "- status: PASS"
  else
    record "- status: FAIL"
    record "- log: \`${LOG_FILE}\`"
    exit 1
  fi
  record ""
}

cleanup() {
  local exit_code=$?
  if [ "${PHASE_STATUS}" != "PASS" ] && [ -f "${EVIDENCE_FILE}" ]; then
    record "## Verdict"
    record "- phase: \`${PHASE_ID}\`"
    record "- status: FAIL"
    record "- log: \`${LOG_FILE}\`"
  fi
  exit "${exit_code}"
}
trap cleanup EXIT

run_runtime_core_witness() {
  bash "${ROOT_DIR}/ops/host/validate-phase4-routing-e2e.sh" --core-only
}

run_lifecycle_recovery_tests() {
  cd "${ROOT_DIR}/apps/api"

  if [ ! -d ".venv" ]; then
    echo "ERROR: apps/api/.venv not found."
    return 1
  fi

  # shellcheck source=/dev/null
  . .venv/bin/activate

  pytest -q \
    tests/test_api.py::test_session_create_private_returns_501 \
    tests/test_api.py::test_session_create_uppercase_tier_rejected \
    tests/test_api.py::test_session_create_requires_auth \
    tests/test_api.py::test_session_create_public_returns_running \
    tests/test_api.py::test_session_create_enforces_user_limit \
    tests/test_api.py::test_session_create_exhausts_gpu_capacity \
    tests/test_api.py::test_session_stop_owner_marks_stopping_and_is_idempotent \
    tests/test_api.py::test_session_stop_forbidden_for_other_user \
    tests/test_api.py::test_session_stop_terminal_row_returns_current_state \
    tests/test_api.py::test_session_create_runtime_failure_marks_error \
    tests/test_concurrency.py \
    tests/test_session_recovery.py \
    tests/test_poller_sla.py \
    tests/test_chaos.py \
    tests/test_main_lifecycle.py::test_healthz_returns_503_when_recovery_enabled_without_live_thread \
    tests/test_main_lifecycle.py::test_healthz_returns_200_with_live_recovery_thread
}

main() {
  if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    usage
    exit 0
  fi

  require_cmd bash

  mkdir -p "${EVIDENCE_DIR}"
  : >"${LOG_FILE}"

  {
    echo "## Phase 3 Lifecycle and Recovery Evidence ($(date -u +%F))"
    echo ""
    echo "Generated by: \`ops/host/validate-phase3-lifecycle-recovery.sh\`"
    echo ""
    echo "Runtime:"
    echo "- run id: \`${RUN_ID}\`"
    echo ""
  } >"${EVIDENCE_FILE}"

  run_check "Runtime Core Witness (Create/Stop/Snapshot)" "run_runtime_core_witness"
  run_check "Lifecycle and Recovery Test Lanes" "run_lifecycle_recovery_tests"

  PHASE_STATUS="PASS"
  record "## Verdict"
  record "- phase: \`${PHASE_ID}\`"
  record "- status: PASS"
  record "- log: \`${LOG_FILE}\`"

  echo "Validation complete: ${EVIDENCE_FILE}"
}

main "$@"
