#!/usr/bin/env bash
#
# Phase 0 host foundation validation.
# Verifies GPU runtime, ZFS primitives, wildcard DNS, and strict TLS.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "${ROOT_DIR}/ops/host/lib/remote-public.sh"
PHASE_ID="phase0-host"
RUN_ID="$(date -u +%Y%m%dT%H%M%SZ)"
EVIDENCE_DIR="${EVIDENCE_DIR:-${ROOT_DIR}/docs/evidence/$(date -u +%F)}"
EVIDENCE_FILE="${EVIDENCE_FILE:-${EVIDENCE_DIR}/${PHASE_ID}-${RUN_ID}.md}"
LOG_FILE="${LOG_FILE:-${EVIDENCE_DIR}/${PHASE_ID}-${RUN_ID}.log}"

ENV_FILE="${ENV_FILE:-${ROOT_DIR}/deploy/compose/.env}"
ZPOOL_NAME="${ZPOOL_NAME:-tank}"
ZFS_WORKSPACE_ROOT="${ZFS_WORKSPACE_ROOT:-tank/medforge/workspaces}"
DOMAIN="${DOMAIN:-}"
PACK_IMAGE="${PACK_IMAGE:-}"

PHASE_STATUS="INCONCLUSIVE"
TMP_DATASET=""
TMP_SNAPSHOT=""
TMP_DATASET_CREATED=false

usage() {
  cat <<'USAGE'
Usage: bash ops/host/validate-phase0-host.sh

Optional env:
  DOMAIN=<medforge domain>
  PACK_IMAGE=<digest-pinned image ref>
  ZPOOL_NAME=tank
  ZFS_WORKSPACE_ROOT=tank/medforge/workspaces
  EVIDENCE_DIR=docs/evidence/<date>
  EVIDENCE_FILE=<explicit markdown path>
  LOG_FILE=<explicit log path>
USAGE
}

require_cmd() {
  local cmd="$1"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "ERROR: required command not found: ${cmd}"
    exit 1
  fi
}

record() {
  local line="$1"
  printf "%s\n" "${line}" >>"${EVIDENCE_FILE}"
}

run_check() {
  local name="$1"
  local cmd="$2"

  record "### ${name}"
  record ""
  record '```bash'
  record "${cmd}"
  record '```'

  if eval "${cmd}" >>"${LOG_FILE}" 2>&1; then
    record "- status: PASS"
  else
    record "- status: FAIL"
    record "- log: \`${LOG_FILE}\`"
    exit 1
  fi
  record ""
}

cleanup() {
  local exit_code=$?

  if [ "${TMP_DATASET_CREATED}" = true ] && [ -n "${TMP_DATASET}" ]; then
    sudo -n zfs destroy -r "${TMP_DATASET}" >/dev/null 2>&1 || true
  fi

  if [ "${PHASE_STATUS}" != "PASS" ] && [ -f "${EVIDENCE_FILE}" ]; then
    record "## Verdict"
    record "- phase: \`${PHASE_ID}\`"
    record "- status: FAIL"
    record "- log: \`${LOG_FILE}\`"
  fi

  exit "${exit_code}"
}
trap cleanup EXIT

zfs_probe() {
  local mountpoint
  local probe
  local readback

  TMP_DATASET="${ZFS_WORKSPACE_ROOT}/phase0-validation-${RUN_ID}"
  TMP_SNAPSHOT="${TMP_DATASET}@phase0-${RUN_ID}"

  sudo -n zfs create -p "${TMP_DATASET}"
  TMP_DATASET_CREATED=true

  mountpoint="$(sudo -n zfs get -H -o value mountpoint "${TMP_DATASET}")"
  probe="phase0-${RUN_ID}"
  printf "%s\n" "${probe}" | sudo -n tee "${mountpoint}/probe.txt" >/dev/null
  readback="$(sudo -n cat "${mountpoint}/probe.txt")"
  if [ "${readback}" != "${probe}" ]; then
    echo "ERROR: ZFS readback mismatch"
    return 1
  fi

  sudo -n zfs snapshot "${TMP_SNAPSHOT}"
  sudo -n zfs list -t snapshot "${TMP_SNAPSHOT}"

  sudo -n zfs destroy "${TMP_SNAPSHOT}"
  sudo -n zfs destroy "${TMP_DATASET}"
  TMP_DATASET_CREATED=false
}

tls_probe() {
  local status web_host api_host

  web_host="$(remote_public_web_host "${DOMAIN}")"
  api_host="$(remote_public_api_host "${DOMAIN}")"

  curl -fsS "https://${web_host}" >/dev/null
  curl -fsS "https://${api_host}/healthz" >/dev/null

  status="$(curl -sS -o /tmp/${PHASE_ID}-session-proxy.out -w '%{http_code}' \
    "https://${api_host}/api/v2/auth/session-proxy" \
    -H "Host: $(remote_public_session_host "phase0check" "${DOMAIN}")")"

  case "${status}" in
    401|403|404)
      ;;
    *)
      echo "ERROR: unexpected wildcard session-proxy status: ${status}"
      return 1
      ;;
  esac

  remote_tls_verify_host "${web_host}"
  remote_tls_verify_host "${api_host}"
}

main() {
  if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    usage
    exit 0
  fi

  require_cmd curl
  require_cmd docker
  require_cmd dig
  require_cmd nvidia-smi
  require_cmd openssl
  require_cmd rg
  require_cmd sudo
  require_cmd zfs
  require_cmd zpool

  if ! sudo -n true >/dev/null 2>&1; then
    echo "ERROR: this script requires passwordless sudo (sudo -n)."
    exit 1
  fi

  if [ -z "${DOMAIN}" ]; then
    DOMAIN="$(remote_read_env_value "${ENV_FILE}" DOMAIN)"
  fi
  if [ -z "${PACK_IMAGE}" ]; then
    PACK_IMAGE="$(remote_read_env_value "${ENV_FILE}" PACK_IMAGE)"
  fi

  if [ -z "${DOMAIN}" ]; then
    echo "ERROR: DOMAIN is required (env or ${ENV_FILE})."
    exit 1
  fi
  if [ -z "${PACK_IMAGE}" ]; then
    echo "ERROR: PACK_IMAGE is required (env or ${ENV_FILE})."
    exit 1
  fi

  mkdir -p "${EVIDENCE_DIR}"
  : >"${LOG_FILE}"

  {
    echo "## Phase 0 Host Foundation Evidence ($(date -u +%F))"
    echo ""
    echo "Generated by: \`ops/host/validate-phase0-host.sh\`"
    echo ""
    echo "Runtime:"
    echo "- domain: \`${DOMAIN}\`"
    echo "- pack image: \`${PACK_IMAGE}\`"
    echo "- zpool: \`${ZPOOL_NAME}\`"
    echo "- workspace root: \`${ZFS_WORKSPACE_ROOT}\`"
    echo "- run id: \`${RUN_ID}\`"
    echo ""
  } >"${EVIDENCE_FILE}"

  run_check "GPU Host Visibility" "nvidia-smi -L && nvidia-smi"
  run_check "GPU Runtime In Container" "docker run --rm --gpus all --entrypoint nvidia-smi '${PACK_IMAGE}'"
  run_check "ZFS Pool Health" "zpool list && zpool status '${ZPOOL_NAME}' && sudo -n zfs list '${ZFS_WORKSPACE_ROOT}'"
  run_check "ZFS Write Read Snapshot Probe" "zfs_probe"
  run_check "Public DNS Resolution" "remote_dns_check_bundle '${DOMAIN}' 'phase0check'"
  run_check "Strict TLS Validation" "tls_probe"

  PHASE_STATUS="PASS"
  record "## Verdict"
  record "- phase: \`${PHASE_ID}\`"
  record "- status: PASS"
  record "- log: \`${LOG_FILE}\`"

  echo "Validation complete: ${EVIDENCE_FILE}"
}

main "$@"
